[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flight-analytics-lakehouse"
version = "0.1.0"
dependencies = [
    "duckdb",
    "pyarrow",
    "polars",
    "httpx",
    "pytest",
    "pydantic",
    "pydantic-settings",
    "dlt[duckdb]",
    "dbt-duckdb",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]