name: 'flight_lakehouse'
version: '1.0.0'
profile: 'flight_lakehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  flight_lakehouse:
    staging:
      +materialized: view
    intermediate:
      +materialized: table