name: 'flight_lakehouse'
version: '1.0.0'
profile: 'flight_lakehouse'

model-paths: ["models"]

vars:
  bts_parquet_path: "../data/processed/**/*.parquet"

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  flight_lakehouse:
    staging:
      +materialized: view

